### ISSUE TITLE
[BUG] Unable to publish Xamarin iOS app to App Store with SkiaSharp with 2.88.4 or 2.88.5

### ISSUE THREAD

**Issue by eddieyanez** [mono/SkiaSharp#2584]
### Description

The error I get when uploading the app to the Apple App Store is:

[Application Loader Error Output]: Asset validation failed Unsupported Architectures. The executable for _AppNameXX_.iOS.app/Frameworks/libSkiaSharp.framework contains unsupported architectures '[arm64e]'.

All works fine on version 2.88.3

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
// some C# code here
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
```

### Expected Behavior

No issues reported when uploading to the Apple App Store.

### Actual Behavior

[Application Loader Error Output]: Asset validation failed Unsupported Architectures. The executable for _AppNameXX_.iOS.app/Frameworks/libSkiaSharp.framework contains unsupported architectures '[arm64e]'.

### Version of SkiaSharp

Other (Please indicate in the description)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (macOS)

### Platform / Operating System

iOS, macOS

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
@rolfbjarne I have added the M1 simulator bits to the fat framework, but it appears that xamarin.ios is not stripping out the simulator arch?

Do I need a special something or is this a bug somewhere?

**Comment by rolfbjarne** [comment]
@mattleibow you can't have a single .framework for both arm64 simulator and arm64 device. You need to use an .xcframework in that case (which contains two different .framework directories, one for the simulator and one for device).

**Comment by mattleibow** [comment]
@rolfbjarne i looked again and I am not doing that... I have 2 frameworks, one for sim and one for device.

I have arm64 and arm64e in the device.

iphonesimulator: x86_64 + arm64
iphoneos: arm64 + arm64e

Is this correct, and do I still need to use an xcframework? I am a tiny bit hesitant as I will have to change the build a bit.

**Comment by rolfbjarne** [comment]
@mattleibow no, you can just drop arm64e, Apple doesn't allow submissions with that architecture, it's of no use right now.

**Comment by mattleibow** [comment]
I fixed this and will try push a preview with the fix soon.

**Comment by mattleibow** [comment]
Literally waiting on CI to finish the build and push :) Hopefully very soon. You can test right now using the preview feed:

 - https://aka.ms/skiasharp-eap/index.json
 - 2.88.6-preview.0.5

If it works for you I can push out today. I am fairly confident, but you should be able to test that.

**Comment by Ark667** [comment]
Its working now, thank you!

**Comment by baneageorge** [comment]
I also had the same problem with v2.88.5. Strangely enough, when trying to upload from VS I was still getting an error. But the same archive I managed to upload with Transporter

**Comment by jimbowyer** [comment]
> 

Thanks - this just unblocked us on iOS app store verification. v 2.88.5 was failing verification inside Xamarin Forms project with 'bSkiaSharp.framework contains unsupported architectures '[arm64e]''. Prerelease 2.88.6-preview.1.2 gets us past that and to a delivered app in submission review :)

**Comment by follesoe** [comment]
Excellent, thanks for the swift fix! Ran into the same issue, verifying using 2.88.6-preview.1.2 now.

**Comment by mattleibow** [comment]
There should be a new stable version filled with fixes! Enjoy!
