### ISSUE TITLE
[BUG] Memory leak at SKRoundRect#Transform?

### ISSUE THREAD

**Issue by ngocdaothanh** [mono/SkiaSharp#994]
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKRoundRect.cs

```cs
public SKRoundRect Transform (SKMatrix matrix)
{
  var destHandle = SkiaApi.sk_rrect_new ();
  if (SkiaApi.sk_rrect_transform (Handle, ref matrix, destHandle)) {
    return new SKRoundRect (destHandle, true);
  }
  return null;
}
```

I think before `return null;`, we need to call `SkiaApi.sk_rrect_delete (destHandle);`.

**Comment by mattleibow** [comment]
Good catch! Thanks!
Fixed in #995

**Comment by ngocdaothanh** [comment]
Looking at the new code:
https://github.com/mono/SkiaSharp/pull/995/files

I think the memory leak hasn't been fixed, because there's no call to `sk_rrect_delete`.

When `sk_rrect_transform` returns `false`, `destHandle` is still not released.

**Comment by ngocdaothanh** [comment]
@mattleibow Please see the above comment ^^

**Comment by mattleibow** [comment]
Oh no. I think something got lost in a merge. Let me fix that.

**Comment by mattleibow** [comment]
Should be there now.
